spring:
  #数据源基本信息
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: langya1315
    driver-class-name: com.mysql.jdbc.Driver
